Create tests directory
a4k/rusbnb pull request #11
Opened 2023-06-13 13:49 UTC by GrishaFly

2023-06-13 16:36 UTC, exp-of-betrayal approved these changes

2023-06-13 16:49 UTC, exp-of-betrayal requested changes
ты создал текстовый файл test в главной дирректории, а не папку. Чтобы создать новую папку надо нажать `new file` -> `create file`. далее откроется меню создания файла:
![image](https://github.com/a4k/rusbnb/assets/119005542/19e66018-b026-4980-a779-5c7758c87aba)
тебе нужно оставить файл пустым а в поле выше написать имя папки/ :

https://github.com/a4k/rusbnb/assets/119005542/c0930e7a-d0d5-4631-bb53-925ff5626db7

после чего вписать имя файла и его содержимое уже

2023-06-13 17:00 UTC, exp-of-betrayal commented
если хочешь увидеть добавились ли какие то файлы или папки то ты должен перейти непосредственно в ветку и посмотреть. это можно сделать следующим образом. зайти во [все ветки](https://github.com/a4k/rusbnb/branches) или перейти непосредственно в ветку  `https://github.com/a4k/rusbnb/tree/имя_ветки` по ее имени

2023-06-14 08:41 UTC, exp-of-betrayal approved these changes

2023-06-14 11:18 UTC, a4k approved these changes

2023-06-14 13:15 UTC, merged